### ISSUE TITLE
[Enhancement] CustomCooldown

### ISSUE THREAD

**Issue by jacobactual** [Predeactor/Predeactor-Cogs#10]
Please change the dm message from `Hey there, can you chill out for a moment?
{channel} is ratelimited and you need to wait {time}! Please note that this channel shares a rate limit with the parent channel category.` to `Slow down! You'll be able to post again in {channel} in {time}.` 

The current message is not exactly "friendly" for a partnered server. I want my users to be able to be aware of their cooldown and at the same time not sound rude.

**Comment by Predeactor** [comment]
The message will get customizable later.

**Comment by Predeactor** [comment]
Resolved by CustomCooldown: v1.3.
