### ISSUE TITLE
[Bug][CustomCooldown] Guild Data Reset

### ISSUE THREAD

**Issue by jacobactual** [Predeactor/Predeactor-Cogs#12]
## Bug description:
When resetting guild data using `[p]slow reset`, it resets the guild data of every server the bot is in globally. 

### Steps to reproduce:
1. Set a slowmode in one server, doesn't matter if it's channel or category
2. Use `[p]slow reset` to reset the guild data in one of the servers
3. Go to the other server where the command wasn't ran and run `[p]slow channel/category list`

### Expected behavior:
The command should reset the guild data its executed in and not globally.

### Versions and infos:
 - Red Version: 3.3.10
 - Host OS: gCloud (Google Cloud Platform)
 - Discord.py Version: 1.3.4

## Others:
I don't know why this part of the code was changed from its purpose. When running the command, its only job is to reset the data in the guild the command was executed in, not to have it reset globally.

**Comment by Predeactor** [comment]
This command will be removed.
Owner shouldn't be able to delete guild(s)'s data as his wish.
If you really want to delete data from your actual guild, use this eval:
`[p]eval bot.get_cog("CustomCooldown").config.guild(ctx.guild).clear()`
