### ISSUE TITLE
[Captcher] doesn't even load

### ISSUE THREAD

**Issue by theMisteryDE** [Predeactor/Predeactor-Cogs#14]
Hey, after reading in cogboard about your cog I thought I give it a try. Couldn't even load it :D

Here's the traceback:

> Exception during loading of cog
> Traceback (most recent call last):
>   File "/root/testenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 119, in _load
>     await bot.load_extension(spec)
>   File "/root/testenv/lib/python3.8/site-packages/redbot/core/bot.py", line 938, in load_extension
>     lib.setup(self)
>   File "/root/.local/share/Red-DiscordBot/data/Tester/cogs/CogManager/cogs/captcher/__init__.py", line 7, in setup
>     bot.add_cog(Captcher(bot))
>   File "/root/.local/share/Red-DiscordBot/data/Tester/cogs/CogManager/cogs/captcher/core.py", line 38, in __init__
>     self.path = bundled_data_path(self)
>   File "/root/testenv/lib/python3.8/site-packages/redbot/core/data_manager.py", line 206, in bundled_data_path
>     raise FileNotFoundError("No such directory {}".format(bundled_path))
> FileNotFoundError: No such directory /root/.local/share/Red-DiscordBot/data/Tester/cogs/CogManager/cogs/captcher/data

It seems that it doesn't create that data folder. Maybe this feedback can help you.

**Comment by Predeactor** [comment]
This issue was already fixed in a commit, please update repo/cog.
