### ISSUE TITLE
[Captcher] A few things that could be improved

### ISSUE THREAD

**Issue by XenonUnity** [Predeactor/Predeactor-Cogs#20]
The server I work on frequently has spam accounts join so captcha verification is essential for the server. Most captcha bots on top.gg or other bot listing sites get defeated by the spam accounts and it's getting incredibly frustrating to manually deal with them. I installed the captcher cog and not a single spam account that joined got past it. The only issue with the cog is that it's a too strict with failed attempts. Some of the captchas it generates are quite difficult to see so multiple attempts are needed but at the moment, a single mistake means you get booted out of the server.

Some of these ideas are repeats of #19 but with my own thoughts and opinions

- The option to refresh/regenerate a new captcha
This would be helpful for the user if the captcha they were given has failed to load or cannot be read. It would probably be ideal to make it refresh with a reaction like 🔄 just to avoid conflicts with sending a message saying "refresh" for example.

- Adjust the limit of failed attempts or disable it completely
As I said in the starting paragraph, the current stage of the cog is if you type it incorrectly once you get kicked from the server. This could be problematic not just for the user but the server too. It is nice to have flexibility for things like this.

- Edit the captcha message
On my server in particular, some people don't understand that they need to go to #roles after verifying. It's annoying when I have to inform people that they have in fact been verified and they need to go to #roles so being able to change either the initial message or success message would be a nice addition.

- Automatic verification
The current captcha bot I am using uses AI/machine learning to do most of the heavy work but sometimes it automatically verifies spam accounts and there isn't much you can do to change that. Maybe, if possible, add a setting that allows you to set the criteria for automatic verification (account age, has profile picture, ksoft bans etc)

**Comment by Predeactor** [comment]
This issue is getting closed to be merged in #19. You can subscribe to the issue to be updated.
