### ISSUE TITLE
Allowing people other than the owner to use sxcu

### ISSUE THREAD

**Issue by DrTipmack** [Predeactor/Predeactor-Cogs#31]
# Options

- [ ] Related to an issue: (Mention the issue)
- [ ] Breaking change(s).
- [x] Related to a cog. xscu

# Contents

Currently, only the owner can upload or shorten images. While I get why this is restricted, as people may abuse it, but it would make sense for mods and admins to use this feature. It would be great if that was the case, as I cannot use this cog when no one else can.

**Comment by Predeactor** [comment]
Archiving repo.
