### ISSUE TITLE
[CustomCooldown] Per message in a channel cooldown

### ISSUE THREAD

**Issue by Jacob-1999** [Predeactor/Predeactor-Cogs#33]
## Options

- [ ] Related to an issue: (Mention the issue)
- [ ] Breaking change(s).
- [x] Related to a cog. (Tell what cog)

## Contents

**Cog:** CustomCooldown

Description: This idea just came to mind. The only slowmode this cog handles is user slowmode and I'm wondering if we could be able to slow down an entire channel. One message per X time in Y channel for entire server.

`[p]slow channel add <channel> <time> [yes_or_no]` - Default would be no for per user slowmode.

I don't think it would be plausible for the category aspect.

**Comment by Predeactor** [comment]
Archiving repo.
