### ISSUE TITLE
Captcha timeout toggle?

### ISSUE THREAD

**Issue by No-WiFi** [Predeactor/Predeactor-Cogs#37]
# Options

- [ ] Related to an issue: (Mention the issue)
- [ ] Breaking change(s).
- [X] Related to a cog. Captcha

# Contents

Request changes made to captcha cog to toggle off timeout

Currently dungeon cog would filter out new users (or to act as potential spam defence) where they get filtered into a role or kicked from the server. Servers that utilise the dungeon cog to filter users into a role would end up being put into a channel where they get to discuss with the server moderators and to allow the moderators to figure out if the account is genuine or troll/spam accounts.

The timeout command is incompatible with this cog to the extent that it would only afford a maximum of 15 minutes before the account is ejected from the server. If there's a way to toggle off timeout per server, this would allow greater flexibility and compatibility with this cog.

**Comment by Predeactor** [comment]
I don't think this is a possible option, Captcha is already made for filtering a part of the users without being the most efficency way to do so, it's preventive.
Conflicting cogs/parameters is something I'm aware of with Captcha, for example, a guild that have set the verification level too high for a proper validation, but that is in fact not Captcha's fault.
I am not an user of the Dungeon cog and I don't know how this one act, how it work and for what context, which is quite problematic for me. As I can understand, it drag suspected users with a chat with moderators. I am unsure how to "fix" this, timeout is a somewhat important part of Captcha and shouldn't be really disabled, you don't want an user stuck in the captcha channel forever, and if the bot shutdown, let's note that bot's message are not deleted.

I'll maybe think about it and talk with the Dungeon's developer about that.

**Comment by No-WiFi** [comment]
Thanks for the prompt response!

I guess the suggestion is more so whether an extension to the timeout settings would be viable to allow individual server owners to manually toggle whether timeout is enabled or otherwise for their own server.

**Comment by Predeactor** [comment]
This will be unpossible, timeout is a necessary option, taking back my argument:
> timeout is a somewhat important part of Captcha and shouldn't be really disabled, you don't want an user stuck in the captcha channel forever, and if the bot shutdown, let's note that bot's message are not deleted.

So that's not an option for me.

**Comment by Predeactor** [comment]
As said, nothing will be done to allow a toggle for timeout, I'm closing this issue.
