### ISSUE TITLE
[CustomCooldown] No DM On Category Slowmode

### ISSUE THREAD

**Issue by jacobactual** [Predeactor/Predeactor-Cogs#9]
## Bug description:
When exceeding a category's timer, you do not receive a DM even with the `dm` option is enabled.

### Steps to reproduce:
1. Enable `dm` if not already enabled
  1.1. _Have your DMs open so the bot can DM you._
2. Set a category slowmode
3. Exceed the cooldown timer

### Expected behavior:
Receive a direct message from the bot telling you how much left on your cooldown

### Versions and infos:
 - Red Version: 3.3.10 
 - Host OS: Ubuntu 20.04 LTS (Google Cloud Platform)
 - Discord.py Version: 1.3.4

**Comment by Predeactor** [comment]
Fixed in version 1.2.2.1.
